FROM ocaml/opam:debian-ocaml-4.12 AS build
RUN cd ~/opam-repository && git pull origin master && git reset --hard a147c4ecea9e6eaa71a0f3bc152d502695c569c4 && opam update
WORKDIR /src
COPY --chown=opam docs-ci-web.opam /src/
RUN sudo mv /usr/bin/opam-2.1 /usr/bin/opam
RUN sudo apt-get install -y "libev-dev" "libgmp-dev" "libssl-dev" "pkg-config"
RUN opam install --deps-only .
ADD --chown=opam . .
RUN sudo chown opam:opam .
RUN --mount=type=cache,target=./_build/,uid=1000,gid=1000 opam config exec -- dune build ./_build/install/default/bin/docs-ci-web && cp ./_build/install/default/bin/docs-ci-web /src/
FROM debian:10
RUN apt-get update && apt-get install rsync libev4 openssh-client curl gnupg2 dumb-init git graphviz libsqlite3-dev ca-certificates netbase gzip bzip2 xz-utils unzip tar -y --no-install-recommends
WORKDIR /var/lib/docs-ci-web
ENTRYPOINT ["dumb-init", "/usr/local/bin/docs-ci-web"]
ENV OCAMLRUNPARAM=a=2
COPY web/static /var/lib/docs-ci-web/static
COPY --from=build /src/docs-ci-web /usr/local/bin/
